### ISSUE TITLE
Embedded Video supported hosts error

### ISSUE THREAD

**Issue by railization** [codevise/pageflow-embedded-video#2]
Pageflow is unable to connect with the supported hosts.
Pageflow::EmbeddedVideo.configure do |config|
  # Remove items to disallow hosts
  # config.supported_hosts = %w(https://www.youtube.com http://www.youtube.com http://vimeo.com)
end
It gives the error of unknown option "supported_hosts" for EnbeddedVideo.
Any help will be greatly appreciated.

**Comment by kioopi** [comment]
The problem seems to be in [lib/pageflow/embedded_video/configuration.rb](https://github.com/codevise/pageflow-embedded-video/blob/master/lib/pageflow/embedded_video/configuration.rb)

In [Line 7](https://github.com/codevise/pageflow-embedded-video/blob/master/lib/pageflow/embedded_video/configuration.rb#L7) supported_hosts is defined as an `attr_reader` and should probably be an `attr_accessor`. 

I don't have a setup to test this right now but i think it should be easy to load a local clone of `pageflow-embedded-video` in your Gemfile to test this.

**Comment by tf** [comment]
So the error occurs when you uncomment that line? Or were does the error occur?

`supported_hosts` should probably really be an `attr_accessor`. But since the array is mutable, there probably is a workaround to edit the array in place. What are you trying to change?

**Comment by railization** [comment]
I have added an initializer in the app for embedded videos but when i run the server it gives that error. But when i commented that line again the error was not there. As far I can infer that the embedded videos plugin will not work if we do not mention the supported hosts ? Right

**Comment by tf** [comment]
No. As stated in the comment string, you only need to change the `supported_hosts` setting if you want to restrict the supported hosts. The given value is actually the default. We should make sure though that the setting is writable - even if this is not necessary in your case.

**Comment by railization** [comment]
Let me try that.

**Comment by railization** [comment]
Hi Tim,

Issues has been fixed thank you for your support.
